config/routes.rb
Rails.application.routes.draw do

  resources :documents

  resources :images

  resources :directories
  root :to => redirect('/directories/new')

  get "/thumbs/:id.thumb.gif", :controller => "images", :action => "serve_thumb"
  get "/displays/:id.display.jpg", :controller => "images", :action => "serve_display"
  

end

app/models/directory.rb
class Directory < ActiveRecord::Base
  has_many :images, dependent: :destroy
  validates :dirpath, presence: true
  validate :directory_must_exist
  
  def directory_must_exist
  	unless dirpath.nil?
	  	unless Pathname(dirpath).exist?
    	  errors.add(:dirpath, ' does not exist')
	    end
	end
  end
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  before_action :set_directory, only: [:show, :edit, :update, :destroy]
skip_before_filter  :verify_authenticity_token
  # GET /directories
  # GET /directories.json
  def index
    @directories = Directory.all
  end

  # GET /directories/1
  # GET /directories/1.json
  def show
      @images = @directory.images
  end

  # GET /directories/new
  def new
	@directory = Directory.new
  end

  # GET /directories/1/edit
  def edit
  end

  # POST /directories
  # POST /directories.json
  def create
	require 'RMagick'
	@directory = Directory.new(directory_params)
	
	if @directory.valid?
	
		# set and test dirpath
		dirpath = Pathname(@directory.dirpath)
		
		# note that dirpath is a Path, therefore handles separators automatically
		hopperdir = dirpath + "hopperflow"
		displaysdir = hopperdir + "displays"
		thumbsdir = hopperdir + "thumbs"
		# create originals, thumbs and displays directories
		Dir.mkdir(hopperdir) unless File.exists?(hopperdir)
		Dir.mkdir(displaysdir) unless File.exists?(displaysdir)
		Dir.mkdir(thumbsdir) unless File.exists?(thumbsdir)

		@directory.save
		
		# for each image, create thumb and display derivative
		Dir.glob(dirpath + "*") do |file|

			# use rmagick to determine whether this file is an image
			begin
				# open file as an image - will raise exception if it isn't
				img = Magick::Image::read(file).first
				
				if img.format != 'TXT'
					extension = File.extname(file) # e.g. ".jpg"
					basename = File.basename(file, extension)
						
					# add image to db
					i = @directory.images.create(
						extension: extension,
						basename: basename,
						width: img.rows,
						height: img.columns,
						size: File.size(file),
						format: img.format
					)
					
					img.resize_to_fit(800,800).write dirpath + "hopperflow" + "displays" + "#{basename}.jpg"
					img.resize_to_fit(200,200).write dirpath + "hopperflow" + "thumbs" + "#{basename}.gif"
				end				
			rescue Exception => e
				# do nothing - it's not an image
			end
		end
	end
	respond_to do |format|
		if @directory.save
			format.html { redirect_to @directory, notice: 'Directory was successfully created.' }
			format.json { render :show, status: :created, location: @directory }
		else
			format.html { render :new }
			format.json { render json: @image.errors, status: :unprocessable_entity }
		end
	end
  end

  # PATCH/PUT /directories/1
  # PATCH/PUT /directories/1.json
  def update
    respond_to do |format|
      if @directory.update(directory_params)
        format.html { redirect_to @directory, notice: 'Directory was successfully updated.' }
        format.json { render :show, status: :ok, location: @directory }
      else
        format.html { render :edit }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directories/1
  # DELETE /directories/1.json
  def destroy
    @directory.destroy
    respond_to do |format|
      format.html { redirect_to directories_url, notice: 'Directory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directory
      @directory = Directory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directory_params
      params.require(:directory).permit(:dirpath)
    end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/views/directories/_form.html.erb
<%= form_for(@directory) do |f| %>
  <% if @directory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory.errors.count, "error") %> prohibited this directory from being saved:</h2>

      <ul>
      <% @directory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dirpath %><br>
    <%= f.text_field :dirpath %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directories/edit.html.erb
<h1>Editing directory</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory %> |
<%= link_to 'Back', directories_path %>

app/views/directories/index.html.erb
<h1>Listing directories</h1>

<table>
  <thead>
    <tr>
      <th>Dirpath</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directories.each do |directory| %>
      <tr>
        <td><%= directory.dirpath %></td>
        <td><%= link_to 'Show', directory %></td>
        <td><%= link_to 'Edit', edit_directory_path(directory) %></td>
        <td><%= link_to 'Destroy', directory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Directory', new_directory_path %>

app/views/directories/new.html.erb
<h1>New directory</h1>

<%= render 'form' %>

<%= link_to 'Back', directories_path %>

app/views/directories/show.html.erb
<div id="header">
<h1>HopperFlow</h1>
<div id="controls">
<input onclick="javascript:hopper2item();" value="Hopper->Item" type="button">
<input onclick="javascript:item2hopper();" value="Hopper<-Item" type="button">
<input onclick="javascript:hopperOrForm(false);" value="Show Form" type="button" id="hopperOrForm">
<br>
<input onclick="javascript:toggleposted();" value="Toggle posted" type="button">
</div>
</div>
<p id="notice"><%= notice %></p>
<p>
  <strong>Dirpath:</strong>
  <%= @directory.dirpath %>
</p>

<%= link_to 'Edit', edit_directory_path(@directory) %> |
<%= link_to 'Back', directories_path %>


<div id="wrapper">
<!--
                  
                  
                  Posted Column
                  
                  
               -->
<div class="column" style="display: none;" id="postedcolumn">
<h2>Posted items (<span id="postedcount"></span>)</h2>
<div id="postedgroup"></div>
</div>
<!--
                  
                  
                  Hopper Column
                  
                  
               -->
<div class="column" id="hoppercolumn">
<h2 id="hopperh2">Hopper (<span id="hoppercount"></span>)</h2>
<h2 id="formh2">Item <span id="itemid-span"></span>
</h2>



<ul class="pagelist" id="hopperlist">

	<% @images.each do |image| 
	@image = image %>

<li class="page" id="row-<%= @image.id %>">
<ul class="pageimages">
<li id="i<%= @image.id %>" class="front image">
<%= render 'images/form' %>
</li>
</ul>
</li>

<% end %>
<!--
                     
                     
                     Form (within hopper column)
                     
                     
                  -->
<ul style="display: none;" id="formlist"></ul>

</div>
<!--
                  
                  
                  Item Column
                  
                  
               -->
<div class="column" id="itemcolumn">
<h2>Item (<span id="itemcount"></span>) <span id="bundlecount"></span>
</h2>
<%= render 'documents/form' %>
<ul class="pagelist" id="itemlist"></ul>
<input value="" id="itemhome" type="hidden">
</div>
<!--
                  
                  
                  Image Column
                  
                  
               -->
<div class="column" id="imagecolumn">
<h2>Images (<span id="imagecount"></span>)</h2>
<ul id="imagelist"></ul>
</div>
</div>