config/routes.rb
Rails.application.routes.draw do

  resources :documents

  resources :images

  resources :directories
  root :to => redirect('/directories/new')

  get "/thumbs/:id.thumb.gif", :controller => "images", :action => "serve_thumb"
  get "/displays/:id.display.jpg", :controller => "images", :action => "serve_display"
  

end

app/models/document.rb
class Document < ActiveRecord::Base
	has_many :images
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:source, :folder, :bundleid, :bundlenum, :itemid, :pages, :ocr, :adjust, :date, :creator, :addressee, :type, :copytype, :script, :envelope, :title, :summary, :notes, :tags, :answers, :answeredby, :hascopy, :copyof)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for :document, remote: true, format: :json, url: documents_path do |f| %>
    <%= f.submit %> <input type="reset">
<%= f.hidden_field :source, :value => "" %>
<%= f.hidden_field :folder, :value => "" %>
<%= f.hidden_field :bundleid, :value => "0" %>
<%= f.hidden_field :bundlenum, :value => "0" %>
<%= f.hidden_field :itemid, :value => "" %>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.number_field :pages %>

    <%= f.label :ocr %><br>
    <%= f.check_box :ocr %>
    <%= f.label :adjust %><br>
    <%= f.check_box :adjust %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :creator %><br>
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :addressee %><br>
    <%= f.text_field :addressee %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.number_field :type %>
    <%= f.label :copytype %><br>
    <%= f.text_field :copytype %>
  </div>
  <div class="field">
    <%= f.label :script %><br>
    <%= f.number_field :script %>
    <%= f.label :envelope %><br>
    <%= f.check_box :envelope %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :answers %><br>
    <%= f.text_field :answers %>
    <%= f.label :answeredby %><br>
    <%= f.text_field :answeredby %>
  </div>
  <div class="field">
    <%= f.label :hascopy %><br>
    <%= f.text_field :hascopy %>
    <%= f.label :copyof %><br>
    <%= f.text_field :copyof %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Folder</th>
      <th>Bundleid</th>
      <th>Bundlenum</th>
      <th>Itemid</th>
      <th>Pages</th>
      <th>Ocr</th>
      <th>Adjust</th>
      <th>Date</th>
      <th>Creator</th>
      <th>Addressee</th>
      <th>Type</th>
      <th>Copytype</th>
      <th>Script</th>
      <th>Envelope</th>
      <th>Title</th>
      <th>Summary</th>
      <th>Notes</th>
      <th>Tags</th>
      <th>Answers</th>
      <th>Answeredby</th>
      <th>Hascopy</th>
      <th>Copyof</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.source %></td>
        <td><%= document.folder %></td>
        <td><%= document.bundleid %></td>
        <td><%= document.bundlenum %></td>
        <td><%= document.itemid %></td>
        <td><%= document.pages %></td>
        <td><%= document.ocr %></td>
        <td><%= document.adjust %></td>
        <td><%= document.date %></td>
        <td><%= document.creator %></td>
        <td><%= document.addressee %></td>
        <td><%= document.type %></td>
        <td><%= document.copytype %></td>
        <td><%= document.script %></td>
        <td><%= document.envelope %></td>
        <td><%= document.title %></td>
        <td><%= document.summary %></td>
        <td><%= document.notes %></td>
        <td><%= document.tags %></td>
        <td><%= document.answers %></td>
        <td><%= document.answeredby %></td>
        <td><%= document.hascopy %></td>
        <td><%= document.copyof %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @document.source %>
</p>

<p>
  <strong>Folder:</strong>
  <%= @document.folder %>
</p>

<p>
  <strong>Bundleid:</strong>
  <%= @document.bundleid %>
</p>

<p>
  <strong>Bundlenum:</strong>
  <%= @document.bundlenum %>
</p>

<p>
  <strong>Itemid:</strong>
  <%= @document.itemid %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @document.pages %>
</p>

<p>
  <strong>Ocr:</strong>
  <%= @document.ocr %>
</p>

<p>
  <strong>Adjust:</strong>
  <%= @document.adjust %>
</p>

<p>
  <strong>Date:</strong>
  <%= @document.date %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @document.creator %>
</p>

<p>
  <strong>Addressee:</strong>
  <%= @document.addressee %>
</p>

<p>
  <strong>Type:</strong>
  <%= @document.type %>
</p>

<p>
  <strong>Copytype:</strong>
  <%= @document.copytype %>
</p>

<p>
  <strong>Script:</strong>
  <%= @document.script %>
</p>

<p>
  <strong>Envelope:</strong>
  <%= @document.envelope %>
</p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @document.summary %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @document.notes %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @document.tags %>
</p>

<p>
  <strong>Answers:</strong>
  <%= @document.answers %>
</p>

<p>
  <strong>Answeredby:</strong>
  <%= @document.answeredby %>
</p>

<p>
  <strong>Hascopy:</strong>
  <%= @document.hascopy %>
</p>

<p>
  <strong>Copyof:</strong>
  <%= @document.copyof %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>